import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val material3: String = "androidx.compose.material3:material3:_"

    public const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    public const val ui_test_manifest: String = "androidx.compose.ui:ui-test-manifest:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val constraintlayout_compose: String =
            "androidx.constraintlayout:constraintlayout-compose:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val orchestrator: String = "androidx.test:orchestrator:_"

    public const val app_cash_paparazzi_gradle_plugin: String =
            "app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:_"

    public const val layoutlib_native_macarm: String =
            "app.cash.paparazzi:layoutlib-native-macarm:_"

    public const val paparazzi: String = "app.cash.paparazzi:paparazzi:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    public const val hilt_android_testing: String = "com.google.dagger:hilt-android-testing:_"

    public const val ktlint: String = "com.pinterest:ktlint:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jacoco_core: String = "org.jacoco:org.jacoco.core:_"

    public const val org_jacoco_report: String = "org.jacoco:org.jacoco.report:_"

    public const val org_jetbrains_kotlin_android_gradle_plugin: String =
            "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:_"

    public const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    public const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    public const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:_"

    public const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter"

    public const val junit_bom: String = "org.junit:junit-bom:_"

    public const val mockito_core: String = "org.mockito:mockito-core:_"
}
