#!/usr/bin/env bash

# Overview:
# Obtains the list of device profiles, obtaining only the lines referring to the hardware profile.
#
# Parameters:
# $1: File location to output the hardware profiles list to.
#
# Warning:
# Ensure that you have the Android SDK on your terminal's PATH variable. You will know it's been
# correctly done when a `which avdmanager` provides an output location for the command.
# See: https://developer.android.com/tools#environment-variables

OUTPUT_FILE=$1

# Create output directory for the output if it doesn't exist already
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# List all hardware profiles
# Filter lines that include "Name:" in them
# Using "space" as a delimiter, grab the 6th instance to the end of the string
# Overwrites the contents of the file referenced by `OUTPUT_FILE`
avdmanager list device | \
grep "Name:" | \
cut -d " " -f6- > "${OUTPUT_FILE}"