#!/usr/bin/env bash

# This script assumes that the dependencies declared within the `Brewfile` are installed.

# Obtains the current version of the project as designated via git conventional commits.
cog -v get-version